blank_issues_enabled: false
contact_links:
  - name: iPipeline GitHub Admins
    email: gitadmins@ipipeline.com
    about: Please email iPipeline GitHub Admins for repo support.
  - name: iPipeline Help
    url: https://ipipeline.cherwellondemand.com/CherwellPortal/iPipelineITSupportPortal
    about: Please report security vulnerabilities here.
